### PR TITLE
feat(logger): add flushLogs method to tests

### LINKED ISSUE #15: Add flush method to empty the `logs` array in logger
When testing there is no way to reset the logs in a test

We have to reuse one instance across packages like this `ui().logger`. UI is a singleton and always carries all logs also from previous tests.

### PR DESCRIPTION
**Pull request by BioPhoton**
### 🔗 Linked issue

#15 

### ❓ Type of change

-  🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- ✨ New feature (a non-breaking change that adds functionality)
-  ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Adds better testing experience. 

Resolves #15 

### 📝 Checklist

- [x] I have read the [contribution guide](https://github.com/poppinss/.github/blob/main/docs/CONTRIBUTING.md).
- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by BioPhoton** [comment]
I was doing that but reverted the changes as it also changed other files that I did not touch. 

So I thought there must be something wrong, either not integrated or format:check is not running in CI.

Anyway if this is how it works here why not. Will format!

**Comment by BioPhoton** [comment]
done

**Comment by thetutlage** [comment]
Looks good. Thanks 👍

**Comment by thetutlage** [comment]
Released. https://github.com/poppinss/cliui/releases/tag/v6.4.0

**Pull request merged**
